In [72]:
!pip install --user psycopg2-binary
!pip install --user seaborn
!pip install --user pandas

Requirement already satisfied: psycopg2-binary in c:\users\duhh\appdata\roaming\python\python37\site-packages (2.7.6.1)
Requirement already satisfied: seaborn in c:\users\duhh\appdata\roaming\python\python37\site-packages (0.9.0)
Requirement already satisfied: pandas>=0.15.2 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from seaborn) (0.23.4)
Requirement already satisfied: numpy>=1.9.3 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from seaborn) (1.15.4)
Requirement already satisfied: scipy>=0.14.0 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from seaborn) (1.1.0)
Requirement already satisfied: matplotlib>=1.4.3 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from seaborn) (3.0.2)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from pandas>=0.15.2->seaborn) (2.7.5)
Requirement already satisfied: pytz>=2011k in c:\users\duhh\appdata\roaming\python\python37\site-packages (from pandas>=0.15.2->seaborn) (2018.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from matplotlib>=1.4.3->seaborn) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from matplotlib>=1.4.3->seaborn) (2.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from matplotlib>=1.4.3->seaborn) (0.10.0)
Requirement already satisfied: six>=1.5 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from python-dateutil>=2.5.0->pandas>=0.15.2->seaborn) (1.11.0)
Requirement already satisfied: setuptools in c:\users\duhh\appdata\local\programs\python\python37\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=1.4.3->seaborn) (39.0.1)
Requirement already satisfied: pandas in c:\users\duhh\appdata\roaming\python\python37\site-packages (0.23.4)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from pandas) (2.7.5)
Requirement already satisfied: pytz>=2011k in c:\users\duhh\appdata\roaming\python\python37\site-packages (from pandas) (2018.7)
Requirement already satisfied: numpy>=1.9.0 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from pandas) (1.15.4)
Requirement already satisfied: six>=1.5 in c:\users\duhh\appdata\roaming\python\python37\site-packages (from python-dateutil>=2.5.0->pandas) (1.11.0)

In [73]:
import seaborn as sns
import pandas as pd
import psycopg2

In [74]:
conn = psycopg2.connect(host="localhost",database="Alyce", user="postgres", password="1234")

# Controle de Frequência de Aulas

# Relatório 01

### Relatório da frequência geral dos alunos por disciplina, incluindo as seguintes informações: campus onde a disciplina é ofertada, curso a qual a disciplina pertence, código da disciplina, nome da disciplina, horas disciplina, nome do professor, nome do aluno, matrícula do aluno e frequência do aluno na disciplina.

Código para obtenção do resultado:

In [75]:
relatorio_01 = pd.read_sql_query("""
SELECT C.nome_disciplina AS Discilpina, C.cod_disciplina, C.horas_disciplina AS Carga_Horaria,  A.campus, B.nome_curso AS Curso, E.nome_professor AS Professor, G.nome_aluno AS Aluno, G.cod_matricula AS Matricula, D.data_aula AS Data_da_aula, D.presenca
FROM Campus A 
JOIN Curso B ON B.FK_Campus_cod_campus = A.cod_campus
JOIN Disciplina C  ON C.FK_Curso_cod_curso = B.cod_curso
JOIN Historico_Aula D  ON D.FK_Disciplina_cod_disciplina = C.cod_disciplina
JOIN Professor E ON E.cod_servidor = D.FK_Professor_cod_servidor
JOIN Gera F  ON F.FK_Historico_Aula_id_historico_aula = D.id_historico_aula
JOIN Aluno G  ON G.cod_matricula = F.FK_Aluno_cod_matricula
ORDER BY C.nome_disciplina
                            """,conn)

In [76]:
relatorio_01

,discilpina,cod_disciplina,carga_horaria,campus,curso,professor,aluno,matricula,data_da_aula,presenca
0,Arquitetura e Organizaçao de Computadores,207,60,Serra,Sistemas de Informação,Leonardo Souza,Matilde Ferreira,20182FIS237,2018-08-28,P
1,Arquitetura e Organizaçao de Computadores,207,60,Serra,Sistemas de Informação,Leonardo Souza,Matilde Ferreira,20182FIS237,2018-08-28,P
2,Arquitetura e Organizaçao de Computadores,207,60,Serra,Sistemas de Informação,Marcos Cavalcanti,Sofia Costa,20181FIS015,2018-08-24,F
3,Arquitetura e Organizaçao de Computadores,207,60,Serra,Sistemas de Informação,Leonardo Souza,Martim Ribeiro,20142MEC188,2018-08-25,P
4,Arquitetura e Organizaçao de Computadores,207,60,Serra,Sistemas de Informação,Leonardo Souza,Martim Ribeiro,20142MEC188,2018-08-25,P
5,Arquitetura e Organizaçao de Computadores,207,60,Serra,Sistemas de Informação,Marcos Cavalcanti,Sofia Costa,20181FIS015,2018-08-24,F
6,Calculo 1,8,90,Serra,Engenharia de Controle e Automação,Marisa Castro,Manuela Rocha,20142AUR222,2018-08-22,F
7,Calculo 1,8,90,Serra,Engenharia de Controle e Automação,Marisa Castro,Camila Cavalcanti,20151ADM873,2018-08-29,F
8,Calculo 1,8,90,Serra,Engenharia de Controle e Automação,Marisa Castro,Manuela Rocha,20142AUR222,2018-08-22,F
9,Calculo 1,8,90,Serra,Engenharia de Controle e Automação,Marisa Castro,Camila Cavalcanti,20151ADM873,2018-08-29,F
10,Estatistica,1275,60,Colatina,Administração,Diego Almeida,Camila Cavalcanti,20151ADM873,2018-08-26,P
11,Estatistica,1275,60,Colatina,Administração,Diego Almeida,Camila Cavalcanti,20151ADM873,2018-08-26,P
12,Filosofia,229,30,Vitoria,Licenciatura em Letras/Português,Cauã Souza,Camila Cavalcanti,20151ADM873,2018-08-23,P
13,Filosofia,229,30,Vitoria,Licenciatura em Letras/Português,Cauã Souza,Camila Cavalcanti,20151ADM873,2018-08-23,P
14,Historia da educaçao,1908,30,Vitoria,Licenciatura em Letras/Português,Emilly Ribeiro,Leonardo Ribeiro,20162MAT003,2018-08-27,F
15,Historia da educaçao,1908,30,Vitoria,Licenciatura em Letras/Português,Emilly Ribeiro,Leonardo Ribeiro,20162MAT003,2018-08-27,F
16,Maquinas de Fluxo,12,60,Aracruz,Engenharia Mecânica,Mariana Rocha,Gustavo Santos,20171AUT552,2018-08-21,P
17,Maquinas de Fluxo,12,60,Aracruz,Engenharia Mecânica,Mariana Rocha,Gustavo Santos,20171AUT552,2018-08-21,P
18,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-28,F
19,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Leonardo Ribeiro,20162MAT003,2018-08-20,P
20,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-30,F
21,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Leonardo Ribeiro,20162MAT003,2018-08-20,P
22,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-08-24,P
23,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-08-27,F
24,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-08-29,F
25,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-08-31,F
26,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-03,F
27,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-05,F
28,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-07,F
29,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-10,F
30,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-12,F
31,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-14,F
32,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-17,F
33,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-19,F
34,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-19,P
35,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-22,P
36,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-24,F
37,Matematica Discreta,23,60,Serra,Sistemas de Informação,Lara Dias,Camila Cavalcanti,20151ADM873,2018-09-26,F

# Relatorio 02

### Relatório da frequência individual do aluno por disciplina, incluindo as seguintes informações: código da disciplina, nome da disciplina, nome do professor, nome do aluno, código de matrícula do aluno, frequência do aluno na disciplina, data da aula, horas disciplina, hora de entrada e saída do aluno.

codigo para obtenção do resultado:

In [77]:
relatorio_02 = pd.read_sql_query("""
SELECT G.nome_aluno, G.cod_matricula, D.presenca, D.data_aula, C.horas_disciplina, D.horario_inicio, D.horario_saida, C.cod_disciplina, C.nome_disciplina, E.nome_professor
FROM Campus A 
JOIN Curso B ON B.FK_Campus_cod_campus = A.cod_campus
JOIN Disciplina C  ON C.FK_Curso_cod_curso = B.cod_curso
JOIN Historico_Aula D ON D.FK_Disciplina_cod_disciplina = C.cod_disciplina
JOIN Professor E ON E.cod_servidor = D.FK_Professor_cod_servidor
JOIN Gera F  ON F.FK_Historico_Aula_id_historico_aula = D.id_historico_aula
JOIN Aluno G ON G.cod_matricula = F.FK_Aluno_cod_matricula
WHERE G.cod_matricula = '20151ADM873' AND  C.cod_disciplina= '23'
                            """,conn)

In [78]:
relatorio_02

,nome_aluno,cod_matricula,presenca,data_aula,horas_disciplina,horario_inicio,horario_saida,cod_disciplina,nome_disciplina,nome_professor
0,Camila Cavalcanti,20151ADM873,P,2018-08-24,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
1,Camila Cavalcanti,20151ADM873,F,2018-08-27,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
2,Camila Cavalcanti,20151ADM873,F,2018-08-29,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
3,Camila Cavalcanti,20151ADM873,F,2018-08-31,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
4,Camila Cavalcanti,20151ADM873,F,2018-09-03,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
5,Camila Cavalcanti,20151ADM873,F,2018-09-05,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
6,Camila Cavalcanti,20151ADM873,F,2018-09-07,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
7,Camila Cavalcanti,20151ADM873,F,2018-09-10,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
8,Camila Cavalcanti,20151ADM873,F,2018-09-12,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
9,Camila Cavalcanti,20151ADM873,F,2018-09-14,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
10,Camila Cavalcanti,20151ADM873,F,2018-09-17,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
11,Camila Cavalcanti,20151ADM873,F,2018-09-19,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
12,Camila Cavalcanti,20151ADM873,P,2018-09-19,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
13,Camila Cavalcanti,20151ADM873,P,2018-09-22,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
14,Camila Cavalcanti,20151ADM873,F,2018-09-24,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
15,Camila Cavalcanti,20151ADM873,F,2018-09-26,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
16,Camila Cavalcanti,20151ADM873,F,2018-09-28,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias
17,Camila Cavalcanti,20151ADM873,F,2018-09-30,60,07:50:00,09:30:00,23,Matematica Discreta,Lara Dias

## Relatório 03

### Relatório geral de alunos por disciplina, incluindo as seguintes informações: código da disciplina, nome da disciplina, horas disciplina, nome do professor, campus onde a disciplina é ofertada, curso da disciplina ofertada, nome do aluno, matrícula do aluno, curso do aluno.

codigo para obtenção do resultado:

In [79]:
relatorio_03 = pd.read_sql_query("""
SELECT DISTINCT C.cod_disciplina, C.nome_disciplina, C.horas_disciplina, E.nome_professor, A.campus, B.nome_curso, G.nome_aluno, G.cod_matricula
FROM Campus A 
JOIN Curso B ON B.FK_Campus_cod_campus = A.cod_campus
JOIN Disciplina C ON C.FK_Curso_cod_curso = B.cod_curso
JOIN Historico_Aula D ON D.FK_Disciplina_cod_disciplina = C.cod_disciplina
JOIN Professor E ON E.cod_servidor = D.FK_Professor_cod_servidor
JOIN Gera F ON F.FK_Historico_Aula_id_historico_aula = D.id_historico_aula
JOIN Aluno G ON G.cod_matricula = F.FK_Aluno_cod_matricula
ORDER BY C.nome_disciplina
                            """,conn)

In [80]:
relatorio_03

,cod_disciplina,nome_disciplina,horas_disciplina,nome_professor,campus,nome_curso,nome_aluno,cod_matricula
0,207,Arquitetura e Organizaçao de Computadores,60,Leonardo Souza,Serra,Sistemas de Informação,Martim Ribeiro,20142MEC188
1,207,Arquitetura e Organizaçao de Computadores,60,Leonardo Souza,Serra,Sistemas de Informação,Matilde Ferreira,20182FIS237
2,207,Arquitetura e Organizaçao de Computadores,60,Marcos Cavalcanti,Serra,Sistemas de Informação,Sofia Costa,20181FIS015
3,8,Calculo 1,90,Marisa Castro,Serra,Engenharia de Controle e Automação,Camila Cavalcanti,20151ADM873
4,8,Calculo 1,90,Marisa Castro,Serra,Engenharia de Controle e Automação,Manuela Rocha,20142AUR222
5,1275,Estatistica,60,Diego Almeida,Colatina,Administração,Camila Cavalcanti,20151ADM873
6,229,Filosofia,30,Cauã Souza,Vitoria,Licenciatura em Letras/Português,Camila Cavalcanti,20151ADM873
7,1908,Historia da educaçao,30,Emilly Ribeiro,Vitoria,Licenciatura em Letras/Português,Leonardo Ribeiro,20162MAT003
8,12,Maquinas de Fluxo,60,Mariana Rocha,Aracruz,Engenharia Mecânica,Gustavo Santos,20171AUT552
9,23,Matematica Discreta,60,Lara Dias,Serra,Sistemas de Informação,Camila Cavalcanti,20151ADM873
10,23,Matematica Discreta,60,Lara Dias,Serra,Sistemas de Informação,Leonardo Ribeiro,20162MAT003

## Relatório 04

### Relatório de frequência nas disciplinas ofertadas por professor, incluindo as seguintes informações: código do servidor, nome do professor, código da disciplina, nome da disciplina, horas disciplina, campus onde a disciplina foi ofertada, média de frequência dos alunos, média de reprovação por falta.

codigo para obtenção do resultado:

In [81]:
relatorio_04 = pd.read_sql_query("""
                            SELECT E.cod_servidor, E.nome_professor, C.cod_disciplina, C.nome_disciplina, C.horas_disciplina, A.campus, G.nome_aluno AS Aluno_reprovado, D.presenca
FROM Campus A 
JOIN Curso B ON B.FK_Campus_cod_campus = A.cod_campus
JOIN Disciplina C ON C.FK_Curso_cod_curso = B.cod_curso
JOIN Historico_Aula D ON D.FK_Disciplina_cod_disciplina = C.cod_disciplina
JOIN Professor E ON E.cod_servidor = D.FK_Professor_cod_servidor
JOIN Gera F ON F.FK_Historico_Aula_id_historico_aula = D.id_historico_aula
JOIN Aluno G ON G.cod_matricula = F.FK_Aluno_cod_matricula
WHERE  D.presenca= 'F'

                            """,conn)

In [82]:
relatorio_04

,cod_servidor,nome_professor,cod_disciplina,nome_disciplina,horas_disciplina,campus,aluno_reprovado,presenca
0,2007IFES023,Marisa Castro,8,Calculo 1,90,Serra,Manuela Rocha,F
1,2000IFES128,Marcos Cavalcanti,207,Arquitetura e Organizaçao de Computadores,60,Serra,Sofia Costa,F
2,1999IFES005,Emilly Ribeiro,1908,Historia da educaçao,30,Vitoria,Leonardo Ribeiro,F
3,2007IFES023,Marisa Castro,8,Calculo 1,90,Serra,Camila Cavalcanti,F
4,2007IFES023,Marisa Castro,8,Calculo 1,90,Serra,Manuela Rocha,F
5,2000IFES128,Marcos Cavalcanti,207,Arquitetura e Organizaçao de Computadores,60,Serra,Sofia Costa,F
6,1999IFES005,Emilly Ribeiro,1908,Historia da educaçao,30,Vitoria,Leonardo Ribeiro,F
7,2007IFES023,Marisa Castro,8,Calculo 1,90,Serra,Camila Cavalcanti,F
8,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
9,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
10,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
11,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
12,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
13,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
14,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
15,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
16,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
17,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
18,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
19,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
20,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
21,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F
22,2014IFES001,Lara Dias,23,Matematica Discreta,60,Serra,Camila Cavalcanti,F

## Relatório 05

### Relatório de todas as disciplinas ofertadas por campus, incluindo as seguintes informações: código da disciplina, nome da disciplina, horas disciplina, nome do professor, curso onde a disciplina está alocada, campus onde a disciplina é ofertada.

codigo para obtenção do resultado:

In [83]:
relatorio_05 = pd.read_sql_query("""
SELECT C.cod_disciplina, C.nome_disciplina, C.horas_disciplina,  B.nome_curso , A.campus, E.nome_professor
FROM Campus A 
JOIN Curso B ON B.FK_Campus_cod_campus = A.cod_campus
JOIN Disciplina C ON C.FK_Curso_cod_curso = B.cod_curso
JOIN Historico_Aula D ON D.FK_Disciplina_cod_disciplina = C.cod_disciplina
JOIN Professor E ON E.cod_servidor = D.FK_Professor_cod_servidor
ORDER BY C.horas_disciplina
                            """,conn)

In [84]:
relatorio_05

,cod_disciplina,nome_disciplina,horas_disciplina,nome_curso,campus,nome_professor
0,229,Filosofia,30,Licenciatura em Letras/Português,Vitoria,Cauã Souza
1,1908,Historia da educaçao,30,Licenciatura em Letras/Português,Vitoria,Emilly Ribeiro
2,207,Arquitetura e Organizaçao de Computadores,60,Sistemas de Informação,Serra,Marcos Cavalcanti
3,207,Arquitetura e Organizaçao de Computadores,60,Sistemas de Informação,Serra,Leonardo Souza
4,1275,Estatistica,60,Administração,Colatina,Diego Almeida
5,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
6,12,Maquinas de Fluxo,60,Engenharia Mecânica,Aracruz,Mariana Rocha
7,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
8,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
9,207,Arquitetura e Organizaçao de Computadores,60,Sistemas de Informação,Serra,Leonardo Souza
10,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
11,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
12,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
13,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
14,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
15,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
16,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
17,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
18,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
19,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
20,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
21,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
22,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
23,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
24,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
25,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
26,23,Matematica Discreta,60,Sistemas de Informação,Serra,Lara Dias
27,8,Calculo 1,90,Engenharia de Controle e Automação,Serra,Marisa Castro
28,8,Calculo 1,90,Engenharia de Controle e Automação,Serra,Marisa Castro